### ISSUE TITLE
Missing timezone - schedule-expression-timezone

### ISSUE THREAD

**Issue by akremer-pgbc** [clouddrove/terraform-aws-cloudwatch-event-rule#10]
Hi.
As per blog from AWS we have a new function to include the timezone.
Can we please include this into the module?
Attribute: schedule-expression-timezone

https://aws.amazon.com/blogs/compute/introducing-amazon-eventbridge-scheduler/

Thanks.
André

**Comment by mamrajyadav** [comment]
Hi @akremer-pgbc schedule-expression-timezone this attribute not available in terraform resources.
