### ISSUE TITLE
input transformer - input_template

### ISSUE THREAD

**Issue by nadavtsa** [clouddrove/terraform-aws-cloudwatch-event-rule#5]
Hi, 
By your documentation it seems that one can define the input path of the input transformer but there is
no argument to add the input_template (the message which uses the fields saved in the input_path).

Can you add it or am I missing someting?

Thank you :)

**Comment by Bobby8249** [comment]
please check the latest code it has  input transformer and input path both . but use only once at a time otherwise it will conflict
